# Generated by Django 6.1.2 on 2026-10-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accountValue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('currency', models.CharField(max_length=3)),
                ('fees', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('executed_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('external_id',), name='unique_trade_per_account')],
            },
        ),
    ]
